### PR TITLE
Add link to hosted API in README

### PR DESCRIPTION
**Pull request by chrisvxd**
This is a proposal to add a link to the hosted API as per discussion in #142.

I've not added the full button described in [my comment](https://github.com/IonicaBizau/scrape-it/issues/142#issuecomment-560508742) as I wanted to keep your README clean.

Happy to discuss payouts via Slack.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Maybe we can make a section for that.

**Comment by chrisvxd** [comment]
Sure, I can do something like this:

image

Also could do below the installation

image

Let me know your preference! Also happy to tweak wording.

**Comment by chrisvxd** [comment]
Hey @IonicaBizau! Hope you had a great xmas. Didn't hear back, so just wanted to check in and see if you had any thoughts on the above?

**Comment by IonicaBizau** [comment]
Will check it tomorrow.

**Pull request merged**
